framework:
    rate_limiter:
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'

security:
    access_decision_manager:
        strategy: unanimous
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: false
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\ApiLoginSuccessHandler
                failure_handler: App\Security\ApiLoginFailureHandler
            logout:
                path: /api/logout
                invalidate_session: true

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/authenticated, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
#        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/api/*, roles: ROLE_USER }

when@prod:
    security:
        firewalls:
                login_throttling:
                    limiter: app.login_rate_limiter
