controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /api/login
    methods: ['POST']
logout:
    path: /api/logout
    methods: ['POST']
